export const regParentesis = /^(.*)\((.*)\)$/;

export const Path = {
    Base: '/',
    Load: '/cargar',
    Order: '/orden',
    Codes: '/codigos',
    Catalogue: '/catalogo',
    SiigoIns: '/insumos-siigo',
    SiigoTel: '/telas-siigo',
    SiigoPro: '/productos-siigo',
    LiderIns: '/insumos-lider',
    LiderTel: '/telas-lider',
    LiderPro: '/productos-lider',
    Tallas: '/tallas',
    Colors: '/colores',
    Bodega: '/bodegas',
    Equivalent: '/equivalencias',
    Insumos: '/insumos',
    Telas: '/telas',
}

export const ErrorMessages = {
    length: {
        tipoComprobante: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoComprobante: 'El codigo de comprobante tiene que ser de longitud 3',
        numeroComprobante: 'El numero de comprobante tiene que ser de longitud 11',
        cuantaContable: 'la cuenta contable tiene que ser de longitud 10',
        debitoCredito: 'El tipo de comprobante tiene que ser de longitud 1',
        valorSecuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        anioDocumento: 'El tipo de comprobante tiene que ser de longitud 1',
        mesDocumento: 'El tipo de comprobante tiene que ser de longitud 1',
        diaDocumento: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoVendedor: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoCiudad: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoZona: 'El tipo de comprobante tiene que ser de longitud 1',
        secuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        centroCosto: 'El tipo de comprobante tiene que ser de longitud 1',
        subcentroCosto: 'El tipo de comprobante tiene que ser de longitud 1',
        NIT: 'El tipo de comprobante tiene que ser de longitud 1',
        sucursal: 'El tipo de comprobante tiene que ser de longitud 1',
        descripcionSecuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroCheque: 'El tipo de comprobante tiene que ser de longitud 1',
        comprobanteAnulado: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoMotivoDevolucion: 'El tipo de comprobante tiene que ser de longitud 1',
        formaPago: 'El tipo de comprobante tiene que ser de longitud 1',
        valorCargoSecuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        valorDescuentoSecuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        facturaElectronica: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroFacturaElectronica: 'El tipo de comprobante tiene que ser de longitud 1',
        prefijoOrden: 'El tipo de comprobante tiene que ser de longitud 1',
        consecutivoOrden: 'El tipo de comprobante tiene que ser de longitud 1',
        prefijoOrdenEntrega: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroOrdenEntrega: 'El tipo de comprobante tiene que ser de longitud 1',
        anioFechaOrdenEntrega: 'El tipo de comprobante tiene que ser de longitud 1',
        mesFechaOrdenEntrega: 'El tipo de comprobante tiene que ser de longitud 1',
        diaFechaOrdenEntrega: 'El tipo de comprobante tiene que ser de longitud 1',
        ingresoTerceros: 'El tipo de comprobante tiene que ser de longitud 1',
        fechaActualizacionDoc: 'El tipo de comprobante tiene que ser de longitud 1',
        horaActualizacionDoc: 'El tipo de comprobante tiene que ser de longitud 1',
        porcentajeAlimentosUltraprocesados: 'El tipo de comprobante tiene que ser de longitud 1',
        valorAlimentosUltraprocesados: 'El tipo de comprobante tiene que ser de longitud 1',
        valorBebidasAzucaradas: 'El tipo de comprobante tiene que ser de longitud 1',
        porcentajeIVASecuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        valorIVASecuencia: 'El tipo de comprobante tiene que ser de longitud 1',
        baseRetencion: 'El tipo de comprobante tiene que ser de longitud 1',
        baseCuentasMarcadasReteiva: 'El tipo de comprobante tiene que ser de longitud 1',
        secuenciaGravadaExcenta: 'El tipo de comprobante tiene que ser de longitud 1',
        porcentajeAIU: 'El tipo de comprobante tiene que ser de longitud 1',
        baseIVAAIU: 'El tipo de comprobante tiene que ser de longitud 1',
        valorTotalImpocomsumo: 'El tipo de comprobante tiene que ser de longitud 1',
        lineaProducto: 'El tipo de comprobante tiene que ser de longitud 1',
        grupoProducto: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoProducto: 'El tipo de comprobante tiene que ser de longitud 1',
        cantidad: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoBodega: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoUbicacion: 'El tipo de comprobante tiene que ser de longitud 1',
        cantidadFactorConversion: 'El tipo de comprobante tiene que ser de longitud 1',
        operadorFactorConversion: 'El tipo de comprobante tiene que ser de longitud 1',
        valorFactorConversion: 'El tipo de comprobante tiene que ser de longitud 1',
        clasificacion: 'El tipo de comprobante tiene que ser de longitud 1',
        gruposActivos: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoActivo: 'El tipo de comprobante tiene que ser de longitud 1',
        adicionMejora: 'El tipo de comprobante tiene que ser de longitud 1',
        vecesAdicionalesADepreciar: 'El tipo de comprobante tiene que ser de longitud 1',
        vecesADepreciarNIIF: 'El tipo de comprobante tiene que ser de longitud 1',
        numerpDocProveedor: 'El tipo de comprobante tiene que ser de longitud 1',
        prefijoDocProveedor: 'El tipo de comprobante tiene que ser de longitud 1',
        anioDocProveedor: 'El tipo de comprobante tiene que ser de longitud 1',
        mesDocProveedor: 'El tipo de comprobante tiene que ser de longitud 1',
        diaDocProveedor: 'El tipo de comprobante tiene que ser de longitud 1',
        tipoDocPedido: 'El tipo de comprobante tiene que ser de longitud 1',
        codigoComprobantePedido: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroComprobantePedido: 'El tipo de comprobante tiene que ser de longitud 1',
        secuenciaPedido: 'El tipo de comprobante tiene que ser de longitud 1',
        tipoMonedaElaboracion: 'El tipo de comprobante tiene que ser de longitud 1',
        tipoComprobanteCruce: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroDocCruce: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroVencimiento: 'El tipo de comprobante tiene que ser de longitud 1',
        anioVencimientoDocCruce: 'El tipo de comprobante tiene que ser de longitud 1',
        mesVencimientoDocCruce: 'El tipo de comprobante tiene que ser de longitud 1',
        diaVencimientoDocCruce: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroCajaAsociadaComprobante: 'El tipo de comprobante tiene que ser de longitud 1',
        descripcionComentarios: 'El tipo de comprobante tiene que ser de longitud 1',
        inconterm: 'El tipo de comprobante tiene que ser de longitud 1',
        descripcionExportacion: 'El tipo de comprobante tiene que ser de longitud 1',
        medioTransporte: 'El tipo de comprobante tiene que ser de longitud 1',
        paisOrigen: 'El tipo de comprobante tiene que ser de longitud 1',
        ciudadOrigen: 'El tipo de comprobante tiene que ser de longitud 1',
        paisDestino: 'El tipo de comprobante tiene que ser de longitud 1',
        ciudadDestino: 'El tipo de comprobante tiene que ser de longitud 1',
        pesoNeto: 'El tipo de comprobante tiene que ser de longitud 1',
        pesoBruto: 'El tipo de comprobante tiene que ser de longitud 1',
        unidadMedidaNeto: 'El tipo de comprobante tiene que ser de longitud 1',
        unidadMedidaBruto: 'El tipo de comprobante tiene que ser de longitud 1',
        conceptoFacturacionBloque: 'El tipo de comprobante tiene que ser de longitud 1',
        datosEstablecimiento: 'El tipo de comprobante tiene que ser de longitud 1',
        numeroEstablecimiento: 'El tipo de comprobante tiene que ser de longitud 1',
    }
}

export const FILES_NAME = {
    Bodegas: 'bodegas',
    Colores: 'colores',
    Tallas: 'tallas',
    LiderProds: 'productos_lider',
    SiigoProds: 'productos_siigo',
    LiderTelas: 'telas_lider',
    SiigoTelas: 'telas_siigo',
    LiderInsum: 'insumos_lider',
    SiigoInsum: 'insumos_siigo',

    CodesNameInsum: 'Códigos Insumos',
    CodesNameTelas: 'Códigos Telas',
    CodesNameProds: 'Códigos Terminados',
    CodesNameProce: 'Códigos Proceso',
    CodesNameTalla: 'Códigos Tallas',
    CodesNamecolor: 'Códigos Colores',
    CodesNameBodeg: 'Códigos Bodegas',

    CreditosInsumos:     'productosInsumos',
    CreditosTelas:       'productosTelas',
    CreditosTerminados:  'productosTerminados',
    CreditosTallas:      'productosTallas',
}